name: app
description: Mobile client for handling cloud service based on raspberry pi.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  drag_select_grid_view: ^0.5.1
  equatable: ^2.0.3
  expandable: ^5.0.1
  file_picker: ^4.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_speed_dial: ^4.6.6
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  leancode_lint: ^1.0.0
  material_design_icons_flutter: ^5.0.5955
  shared_preferences: ^2.0.8

dev_dependencies:
  auto_route_generator: ^2.1.0
  #  flutter pub run build_runner build --delete-conflicting-outputs
  #  flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/thumbnails/
