name: app
description: Mobile client for handling cloud service based on raspberry pi.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  bloc: ^7.0.0
  chopper: ^4.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  drag_select_grid_view: ^0.5.1
  equatable: ^2.0.3
  expandable: ^5.0.1
  file_picker: ^4.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^5.0.2
  flutter_speed_dial: ^4.6.6
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  jwt_decoder: ^2.0.1
  leancode_lint: ^1.0.0
  material_design_icons_flutter: ^5.0.5955
  mime: ^1.0.1
  password_strength: ^0.2.0
  path: ^1.8.0
  pedantic: ^1.11.1
  provider: ^6.0.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.8

dev_dependencies:
  auto_route_generator: ^2.2.0
  #  flutter pub run build_runner build --delete-conflicting-outputs
  #  flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.0
  chopper_generator: ^4.0.3
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  swagger_dart_code_generator: ^2.2.5+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/thumbnails/
